spring:
  application:
    name: tradify

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: tradify-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5432/tradify
    username: tradify
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: market
        format_sql: true
    show-sql: false

finnhub :
  ws :
    url : wss://ws.finnhub.io?token=${FINNHUB_API_KEY}

kafka:
  topics:
    market-ticks: market-ticks

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
